# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Holly Hatcher
title: Aspiring Web Developer
email: hatcherparashar@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  modelmade5
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll



about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Hollyt and I'm an aspiring web developer. I am going through a career transformation and while looking for alternate career i came across web development and instantly fell in love with it. I am currently enrolled in a coding bootcamp with code tenderloin and i am also doing self teaching through udemy and freecodecamp. 
  
  I am Highly dependable, determined, and dynamic professional with extensive experience in sales and engineering assistantance. Currently looking to a part of competitive team to gain experience an enhance my skills as a web developer.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Cat APP
        link: modelmade5.github.io/projects/catapp.html
        additional_links:
          - title:  Cat APP
            icon: fab fa-github
            url: modelmade5.github.io/projects
        quote: >
          This was my first project. I learned HTML basics while creating a layout for application on cats.
        description: | # this will include new lines to allow paragraphs
          !--project description--
      - layout: top-middle
        title: Cafe Menu
        link: modelmade5.github.io/projects/cafemenu.html
        additional_links:
          - title:  Cafe Menu
            icon: fab fa-github
            url: modelmade5.github.io/projects
        quote: >
          This project includes the application of cascading style sheets.
        description: | # this will include new lines to allow paragraphs
          !--project description--
  - title: Experience 
    layout: list
    content:
      - layout: left
        title: WEB DEVELOPMENT BOOTCAMP (UDEMY / CODE TENDERLOIN) 
        link: codetenderloin.org
        sub_title: Student
        caption: March 2022 - Present
        quote: >
          Learning web development basics as well as getting fimilar with high level UX/UI design concepts
        description: |
            •	learned about basic elements of frontend web development.
            •	Created responsive, accessible, and beautiful layouts
            •	Created static HTML, CSS and javascript portfolio sites and landing pages.
            •	Learned about complex HTML forms with landing pages
            •	Learned about Javascript functions, and their scope.
 - title: Skills
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        description:
                    •	HTML5
                    •	CSS
                    •	Javascript
                    •	Jquery
                    •	Wordpress
                    •	Front end development
                    •	Gimp
      - layout: right
        description:
                    •	Client Relationship Management
                    •	Website Creation
                    •	Website Maintenance
                    •	Drafting/Design
                    •	Manual Drafting
  - title: Education 
    layout: list 
    content:
      - layout: left
        title: SHELTON COMMUNITY COLLEGE
        caption: 2016 - 2018
        sub_title: ASSOCIATES DEGREE IN DRAFTING
        quote: >
          Shelton State Community College is a public community college in Tuscaloosa, Alabama. Operated by the Alabama State Department of Postsecondary Education, Shelton is one of the largest two-year colleges in the state.
        description: | # this will include new lines to allow paragraphs
          During my time at Shelton I learnt most of my key skills as a drafter which ultimately landed my first job at MCBEE CONSTRUCTION. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in web development i also enjoy creating youtube content.
      
      I alsi like voice recording and providing my voice skills to record audio books as well as voicing cartoons.

      I am a big believer of giving back to my community and in that pursuit i do a lot of voluenter work which involves



footer_show_references: true


# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
